export const SONG_SELECTED = 'SONG_SELECTED';
export const VOLUME_CHANGED = 'VOLUME_CHANGED';
export const REPEAT_MODE_CHANGED = 'REPEAT_MODE_CHANGED';
export const SHUFFLE_TOGGLED = 'SHUFFLE_TOGGLED';
export const PLAYBACK_SPEED_CHANGED = 'PLAYBACK_SPEED_CHANGED';
export const AUTOPLAY_TOGGLED = 'AUTOPLAY_TOGGLED';
