export const SONG_SELECTED = 'SONG_SELECTED';
export const VOLUME_CHANGED = 'VOLUME_CHANGED';
export const REPEAT_MODE_CHANGED = 'REPEAT_MODE_CHANGED';
export const SHUFFLE_TOGGLED = 'SHUFFLE_TOGGLED';
